### ISSUE TITLE
Fintium website content design

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-design#19]
**Description**
Fintium website content design.

**Reference**
- #18 Fintium FinTech Challenge one page website design

**Tasks**
- [ ] Navbar section design.
- [ ] Hero section design.
- [ ] About or event description section design.
- [ ] Schedule section design.
- [ ] Speaker section design.
- [ ] Sponsor section design.
- [ ] Registration page design.
- [ ] Contact page design.
- [ ] Footer section design.
- [ ] #20 Fintium Eventbrite page design.

**Comment by guylepage3** [comment]
Working on this now.

**Comment by guylepage3** [comment]
https://github.com/universelabs/universe-design/issues/18

**Comment by guylepage3** [comment]
[fintium-sell-sheet.pdf](https://github.com/universelabs/universe-design/files/3307260/fintium-sell-sheet.pdf)

**Comment by guylepage3** [comment]
Done
